[global]
name       = "arch-worker"
log_dir    = "~/.hustsync/log/{{.Name}}"
mirror_dir = "~/.hustsync/data"
concurrent = 2
interval   = 360

[manager]
api_base = "http://127.0.0.1:14242"
token    = ""
ca_cert  = ""

[server]
hostname    = "localhost"
listen_addr = "127.0.0.1"
listen_port = 6000
ssl_cert    = ""
ssl_key     = ""

[[mirrors]]
name          = "archlinux"
provider      = "rsync"
upstream      = "rsync://mirrors.tuna.tsinghua.edu.cn/archlinux/"
interval      = 360
timeout       = 86400
exclude_file  = "~/.hustsync/excludes/archlinux.txt"
rsync_options = ["--max-size=2G", "--delete-excluded", "--delete-after"]
size_pattern  = "Total size is ([0-9\\.]+[KMGTP]?)"
